### ISSUE TITLE
currently fails to build without concise args

### ISSUE THREAD

**Issue by mauricefallon** [mitdrc/common_utils#1]
previously concise args was an svn external (on commit 18) now it has to be availabe in the pods build environment (or an external)

alternative solution is to remove concise args from use in common utils

**Comment by patmarion** [comment]
I saw you added concise-args as an external to drc.  So should we remove concise-args from the common_utils/tobuild.txt?  Or remove concise-args from drc externals and add it as git submodule to common_utils?

**Comment by mauricefallon** [comment]
> So should we remove concise-args from the common_utils/tobuild.txt?
> ops, i guess that causes a build failure right now.

i think that a git submodule within common_utils is the right approach as it should build as it previously did. but its poor to need to use a submodule for about 5 minor utilities.

can you add the submodule and have externals/cmake fetch it?

**Comment by patmarion** [comment]
When the external projects are cloned the submodules are automatically initialized, so it should work correctly.

**Comment by mauricefallon** [comment]
perfect

**Comment by patmarion** [comment]
I'll take care of this.

**Comment by patmarion** [comment]
i think this is resolved.
